[ref.liberman2015]
title = "PP attachment ambiguity of the week"
author = "Mark Liberman"
url = "https://languagelog.ldc.upenn.edu/nll/?p=17711"
year = 2015

[ref.wikipedia2020]
title = "Catalan number"
author = "Wikipedia"
url = "https://en.wikipedia.org/w/index.php?title=Catalan_number&oldid=979933953"
year = 2020
